import { useEffect, useState } from 'react';
import { Navigate, Route, Routes } from 'react-router-dom';
import { Navigation } from './components/Navigation';
import { StoryMeta } from './data/stories';
import { LandingPage } from './pages/LandingPage';
import { StoryView } from './pages/StoryView';
import { AboutPage } from './pages/AboutPage';
import { EditorPage } from './pages/EditorPage';
import { ContentEditorPage } from './pages/ContentEditorPage';
import { storyConfigSchema } from './storySchema';
import { withBasePath } from './utils/basePath';
import { contentIndexSchema } from './types/contentIndex';
import { StoryProvider } from './context/StoryContext';

export default function App() {
  const [stories, setStories] = useState<StoryMeta[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadStories = async () => {
      try {
        // Load content index (auto-generated by plugin from /content/stories/)
        const indexPath = withBasePath('/index.json');
        const indexRes = await fetch(indexPath);
        if (!indexRes.ok) {
          console.error('Failed to load content index');
          setLoading(false);
          return;
        }
        
        const indexRaw = await indexRes.json();
        const indexParsed = contentIndexSchema.safeParse(indexRaw);
        if (!indexParsed.success) {
          console.error('Invalid content index format:', indexParsed.error);
          setLoading(false);
          return;
        }

        const storyRegistry = indexParsed.data.stories;

        const loaded = await Promise.all(
          storyRegistry.map(async (reg) => {
            try {
              const configPath = withBasePath(reg.configPath);
              const res = await fetch(configPath);
              const raw = await res.json();
              const parsed = storyConfigSchema.safeParse(raw);
              if (parsed.success) {
                const config = parsed.data;
                // Extract cover from first page's foreground or background
                const firstPage = config.pages?.[0];
                const coverSrc = firstPage?.foreground?.src || firstPage?.background?.src || '';
                return {
                  id: reg.id,
                  title: config.title,
                  subtitle: config.subtitle,
                  description: config.description || config.subtitle || config.title,
                  theme: config.theme,
                  cover: withBasePath(coverSrc),
                  configPath,
                  badge: config.badge,
                  publishedAt: config.publishedAt || new Date().toISOString(),
                } as StoryMeta;
              }
            } catch (e) {
              console.error(`Failed to load story ${reg.id}:`, e);
            }
            return null;
          })
        );
        const validStories = loaded.filter((s) => s !== null) as StoryMeta[];
        // Sort by publishedAt, newest first
        validStories.sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime());
        setStories(validStories);
      } catch (e) {
        console.error('Failed to load stories:', e);
      } finally {
        setLoading(false);
      }
    };
    loadStories();
  }, []);

  if (loading) {
    return (
      <div className="relative min-h-screen bg-surface text-text flex items-center justify-center">
        <div className="text-muted">Loading stories...</div>
      </div>
    );
  }

  return (
    <StoryProvider stories={stories}>
      <div className="relative min-h-screen bg-surface text-text">
        <Navigation stories={stories} />
        <main className="relative min-h-screen px-4 pb-16 pt-10 pl-4 md:px-10 md:pl-80">
          <Routes>
            <Route path="/" element={<LandingPage stories={stories} />} />
            <Route path="/story/:id" element={<StoryView />} />
            <Route path="/about" element={<AboutPage />} />
            <Route path="/editor" element={<EditorPage />} />
            <Route
              path="/editor/home"
              element={<ContentEditorPage file="home.json" title="Home Editor" description="Edit the home page content JSON." />}
            />
            <Route
              path="/editor/about"
              element={<ContentEditorPage file="about.json" title="About Editor" description="Edit the about page content JSON." />}
            />
            <Route path="*" element={<Navigate to="/" replace />} />
          </Routes>
        </main>
      </div>
    </StoryProvider>
  );
}
